/* This file is auto-generated by yum/generate-blobs.pl */
/* DO NOT EDIT THIS FILE! */

#ifndef YUMBLOB_H
#define YUMBLOB_H

#include <stddef.h>
#include <stdint.h>

struct yumBlob {
    size_t originalSize;
    uint8_t *originalData;
    size_t compressedSize;
    const uint8_t *compressedData;

    uint8_t *getData();
    inline size_t getSize() const { return originalSize; };
    void write(const char *fname);
};

namespace blobs {
    extern yumBlob font_32_64_yum;
};
#endif /* YUMBLOB_H */
