// Auto-generated by yum/generate-statues.py
// DO NOT EDIT - regenerate using: python3 yum/generate-statues.py

#ifndef YUMSTATUES_H
#define YUMSTATUES_H

// Target Y coordinate for statue scanning
#define STATUE_TARGET_Y -281

// Number of statues in the target sequence
#define STATUE_COUNT 5

// Statue target for GPS coordinate resolution
struct StatueTarget {
    int x;                    // Global X coordinate
    int displayID;            // Display ID for matching
    const char *name;         // Name (with underscores)
    const char *clothingSet;  // Semicolon-separated clothing IDs
    const char *finalWords;   // Final words (with underscores)
};

// Array of statue targets at Y=-281 for GPS scanning
static const StatueTarget STATUE_TARGETS[STATUE_COUNT] = {
    { -74782, 3078, "BOB_SPOCK", "0;0;0;0;0;0", "IM_SCORPIO_JOE_ON_DISCORD" },
    { -74781, 2464, "STELLA_SPOCK", "0;0;0;0;0;0", "IM_FUCKING_GAY" },
    { -74780, 2404, "ROOSEVELT_SPOCK", "0;0;0;0;0;0", "BYE_BYE" },
    { -74779, 2404, "RAINBOW_SPOCK", "0;0;0;0;0;0", "TO_SPACE_AND_BEYOND" },
    { -74778, 3078, "TYRONE_SPOCK", "0;0;0;0;0;0", "BYE_WORLD!!!!!!" }
};

#endif
