// SLOP WARNING: All code below is generated by an LLM. The concept is valid,
// the output is effective, but the implementation is deranged. Since this is
// effectively a one-shot tool, I don't care enough to improve it.
#include <algorithm>
#include <atomic>
#include <chrono>
#include <cctype>
#include <climits>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <fstream>
#include <mutex>
#include <sstream>
#include <string>
#include <thread>
#include <vector>

#include "minorGems/util/crc32.h"
#include "minorGems/util/random/JenkinsRandomSource.h"

#include "curseWordList_xxd.h"


// Patch these two constants after running:
//   crc-fun calibrate observations.txt
static constexpr bool     kHaveBuiltInCalibration = true;
static constexpr uint64_t kSecretLen              = 21;
static constexpr uint32_t kSecretCrc32            = 0x31426be9u;

// Reflected CRC-32 polynomial (same as minorGems/util/crc32.cpp)
static constexpr uint32_t kCrc32Polynomial = 0xedb88320u;


// --- Word list ---

static std::string upperString(const std::string &s) {
    std::string out = s;
    for (char &c : out) {
        c = static_cast<char>(std::toupper(static_cast<unsigned char>(c)));
    }
    return out;
}

static std::vector<std::string> loadCurseWords() {
    // xxd-embedded curseWordList.txt; filter to <6 chars and uppercase,
    // matching the server's own loading logic.
    std::string data(reinterpret_cast<const char *>(curseWordList_txt),
                     curseWordList_txt_len);
    std::istringstream in(data);
    std::vector<std::string> words;
    std::string word;
    while (in >> word) {
        if (word.size() < 6) {
            words.push_back(upperString(word));
        }
    }
    return words;
}

static const std::vector<std::string> &curseWords() {
    static const std::vector<std::string> words = loadCurseWords();
    return words;
}

static bool wordExists(const std::string &word) {
    const auto &words = curseWords();
    return std::find(words.begin(), words.end(), upperString(word)) != words.end();
}


// --- Jenkins helpers ---
//
// Uses JenkinsRandomSource directly from minorGems. The seeded constructor
// is always used; we never call the clock-seeded no-arg constructor.

static std::vector<std::string> wordsFromSeed(uint32_t seed, int count) {
    const auto &words = curseWords();
    JenkinsRandomSource rng(seed);
    std::vector<std::string> out;
    out.reserve(count);
    for (int i = 0; i < count; i++) {
        int idx = rng.getRandomBoundedInt(0, static_cast<int>(words.size()) - 1);
        out.push_back(words[idx]);
    }
    return out;
}

static bool seedMatchesWords(uint32_t seed, const std::vector<std::string> &expected) {
    const auto &words = curseWords();
    JenkinsRandomSource rng(seed);
    for (const std::string &want : expected) {
        int idx = rng.getRandomBoundedInt(0, static_cast<int>(words.size()) - 1);
        if (words[idx] != want) {
            return false;
        }
    }
    return true;
}


// --- CRC32 combine ---
//
// CRC32 is linear over GF(2), so:
//   CRC32(A || B) = crc32Shift(CRC32(A), len(B)) ^ CRC32(B)
//
// crc32Shift advances a CRC state as if `byteCount` zero bytes were appended.
// This lets us compute CRC32(prefix + secret) knowing only CRC32(prefix),
// CRC32(secret), and len(secret) -- which is the key to calibration.

static uint32_t gf2MatrixTimes(const uint32_t *mat, uint32_t vec) {
    uint32_t sum = 0;
    while (vec != 0) {
        if (vec & 1u) sum ^= *mat;
        vec >>= 1;
        mat++;
    }
    return sum;
}

static void gf2MatrixSquare(uint32_t *square, const uint32_t *mat) {
    for (int i = 0; i < 32; i++) {
        square[i] = gf2MatrixTimes(mat, mat[i]);
    }
}

static uint32_t crc32Shift(uint32_t crc, uint64_t byteCount) {
    if (byteCount == 0) return crc;

    uint32_t odd[32], even[32];

    odd[0] = kCrc32Polynomial;
    uint32_t row = 1;
    for (int i = 1; i < 32; i++) {
        odd[i] = row;
        row <<= 1;
    }

    gf2MatrixSquare(even, odd);
    gf2MatrixSquare(odd, even);

    do {
        gf2MatrixSquare(even, odd);
        if (byteCount & 1u) crc = gf2MatrixTimes(even, crc);
        byteCount >>= 1;
        if (byteCount == 0) break;

        gf2MatrixSquare(odd, even);
        if (byteCount & 1u) crc = gf2MatrixTimes(odd, crc);
        byteCount >>= 1;
    } while (byteCount != 0);

    return crc;
}

static uint32_t crc32Combine(uint32_t crcA, uint32_t crcB, uint64_t lenB) {
    return crc32Shift(crcA, lenB) ^ crcB;
}

// Precomputes the matrix M^n as 32 column vectors, so that
// gf2MatrixTimes(mat, crc) == crc32Shift(crc, n) without rerunning the full
// squaring loop on every call. Used to make the find-curse-names hot loop cheap.
static void buildShiftMatrix(uint64_t n, uint32_t mat[32]) {
    for (int i = 0; i < 32; i++) {
        mat[i] = crc32Shift(static_cast<uint32_t>(1u) << i, n);
    }
}

static uint32_t crc32String(const std::string &s) {
    return crc32(reinterpret_cast<const unsigned char *>(s.data()),
                 static_cast<int>(s.size()));
}


// --- Prefix helpers ---

static std::string propertyPrefix(int x, int y) {
    return std::to_string(x) + "_" + std::to_string(y) + "_";
}

static std::string cursePrefix(const std::string &email) {
    return email + "_";
}


// --- Observation parsing ---

struct Observation {
    int x, y;
    std::vector<std::string> words;
    std::string prefix;
    uint32_t prefixCrc;
};

struct Candidate {
    uint64_t secretLen;
    uint32_t secretCrc32;
};

static bool parseInt(const char *s, int *out) {
    char *end = nullptr;
    long val = std::strtol(s, &end, 10);
    if (end == s || *end != '\0' || val < INT32_MIN || val > INT32_MAX) return false;
    *out = static_cast<int>(val);
    return true;
}

static bool parseUInt64(const char *s, uint64_t *out) {
    char *end = nullptr;
    unsigned long long val = std::strtoull(s, &end, 10);
    if (end == s || *end != '\0') return false;
    *out = static_cast<uint64_t>(val);
    return true;
}

static bool readObservations(const char *path, std::vector<Observation> *out) {
    std::ifstream file(path);
    if (!file) {
        std::fprintf(stderr, "Could not open %s\n", path);
        return false;
    }

    std::string line;
    int lineNum = 0;

    while (std::getline(file, line)) {
        lineNum++;

        size_t comment = line.find('#');
        if (comment != std::string::npos) line.erase(comment);

        std::istringstream ss(line);
        int x = 0, y = 0;
        std::string w0, w1;

        if (!(ss >> x >> y >> w0 >> w1)) {
            // Blank or comment-only line - skip if nothing left
            std::string leftover;
            std::istringstream check(line);
            if (check >> leftover) {
                std::fprintf(stderr, "Bad observation at %s:%d (expected: x y word0 word1)\n",
                             path, lineNum);
                return false;
            }
            continue;
        }

        w0 = upperString(w0);
        w1 = upperString(w1);

        if (!wordExists(w0)) {
            std::fprintf(stderr, "Unknown word '%s' at %s:%d\n", w0.c_str(), path, lineNum);
            return false;
        }
        if (!wordExists(w1)) {
            std::fprintf(stderr, "Unknown word '%s' at %s:%d\n", w1.c_str(), path, lineNum);
            return false;
        }

        Observation obs;
        obs.x = x;
        obs.y = y;
        obs.words = {w0, w1};
        obs.prefix = propertyPrefix(x, y);
        obs.prefixCrc = crc32String(obs.prefix);
        out->push_back(obs);
    }

    if (out->empty()) {
        std::fprintf(stderr, "No observations found in %s\n", path);
        return false;
    }

    return true;
}


// --- Candidate validation ---

static bool candidateMatchesObservation(const Candidate &c, const Observation &obs) {
    uint32_t seed = crc32Combine(obs.prefixCrc, c.secretCrc32, c.secretLen);
    return seedMatchesWords(seed, obs.words);
}

static bool candidateMatchesAll(const Candidate &c, const std::vector<Observation> &obs) {
    for (const Observation &o : obs) {
        if (!candidateMatchesObservation(c, o)) return false;
    }
    return true;
}


// --- Calibration ---

static std::vector<uint32_t> collectMatchingSeeds(const std::vector<std::string> &targetWords) {
    const uint64_t total = 1ULL << 32;
    const uint64_t batchSize = 1ULL << 20;

    unsigned int nThreads = std::thread::hardware_concurrency();
    if (nThreads == 0) nThreads = 1;
    if (nThreads > 64) nThreads = 64;

    std::atomic<uint64_t> next(0);
    std::atomic<uint64_t> done(0);
    std::atomic<bool> running(true);
    std::mutex resultsMutex;
    std::vector<uint32_t> results;

    auto started = std::chrono::steady_clock::now();

    std::thread progressThread([&]() {
        while (running.load()) {
            std::this_thread::sleep_for(std::chrono::seconds(5));
            uint64_t doneNow = done.load();
            double secs = std::chrono::duration<double>(
                std::chrono::steady_clock::now() - started).count();
            std::fprintf(stderr, "  Scanned %.1f%% (%.1fM seeds/s)\n",
                         100.0 * doneNow / total,
                         secs > 0 ? doneNow / secs / 1e6 : 0.0);
        }
    });

    std::vector<std::thread> workers;
    workers.reserve(nThreads);
    for (unsigned int t = 0; t < nThreads; t++) {
        workers.emplace_back([&]() {
            std::vector<uint32_t> local;
            local.reserve(4096);
            while (true) {
                uint64_t start = next.fetch_add(batchSize);
                if (start >= total) break;
                uint64_t end = std::min(start + batchSize, total);
                for (uint64_t i = start; i < end; i++) {
                    uint32_t seed = static_cast<uint32_t>(i);
                    if (seedMatchesWords(seed, targetWords)) {
                        local.push_back(seed);
                    }
                }
                done.fetch_add(end - start);
            }
            std::lock_guard<std::mutex> lock(resultsMutex);
            results.insert(results.end(), local.begin(), local.end());
        });
    }

    for (auto &w : workers) w.join();
    running.store(false);
    progressThread.join();

    std::sort(results.begin(), results.end());
    return results;
}

static int cmdCalibrate(const char *path, uint64_t minLen, uint64_t maxLen) {
    std::vector<Observation> obs;
    if (!readObservations(path, &obs)) return 1;

    std::fprintf(stderr, "Loaded %zu observations (word list: %zu words)\n",
                 obs.size(), curseWords().size());
    std::fprintf(stderr, "Scanning all 2^32 seeds against first observation...\n");

    std::vector<uint32_t> anchorSeeds = collectMatchingSeeds(obs.front().words);
    std::fprintf(stderr, "First observation matched %zu seeds\n", anchorSeeds.size());

    // For each candidate length, precompute crc32Shift(obs[i].prefixCrc, len)
    // for every observation. This avoids rerunning the GF2 matrix squaring
    // ~27M times (once per anchor seed per non-anchor observation).
    // Obs[0] is the anchor: its shifted prefix gives us secretCrc = anchorSeed ^ shift[0],
    // so we only need to actually validate obs[1..n].
    std::vector<Candidate> candidates;
    for (uint64_t len = minLen; len <= maxLen; len++) {
        std::vector<uint32_t> shiftedPrefixes(obs.size());
        for (size_t i = 0; i < obs.size(); i++) {
            shiftedPrefixes[i] = crc32Shift(obs[i].prefixCrc, len);
        }

        for (uint32_t anchorSeed : anchorSeeds) {
            uint32_t secretCrc = anchorSeed ^ shiftedPrefixes[0];

            // Validate against obs[1..n] (obs[0] is guaranteed to pass
            // since anchorSeed was chosen specifically for it)
            bool ok = true;
            for (size_t i = 1; i < obs.size(); i++) {
                uint32_t seed = shiftedPrefixes[i] ^ secretCrc;
                if (!seedMatchesWords(seed, obs[i].words)) {
                    ok = false;
                    break;
                }
            }
            if (!ok) continue;

            candidates.push_back({len, secretCrc});
        }
    }

    if (candidates.empty()) {
        std::printf("No candidates found. Check coordinates/words, or broaden the length range.\n");
        return 2;
    }

    size_t printLimit = std::min<size_t>(candidates.size(), 50);
    std::printf("Found %zu candidate%s:\n",
                candidates.size(), candidates.size() == 1 ? "" : "s");
    for (size_t i = 0; i < printLimit; i++) {
        std::printf("  len=%-4llu  secret_crc32=0x%08x\n",
                    static_cast<unsigned long long>(candidates[i].secretLen),
                    candidates[i].secretCrc32);
    }
    if (candidates.size() > printLimit) {
        std::printf("  ... %zu more; add more observations to disambiguate.\n",
                    candidates.size() - printLimit);
    }

    if (candidates.size() == 1) {
        const Candidate &c = candidates.front();
        std::printf("\nPatch crc-fun.cpp with:\n"
                    "static constexpr bool     kHaveBuiltInCalibration = true;\n"
                    "static constexpr uint64_t kSecretLen              = %llu;\n"
                    "static constexpr uint32_t kSecretCrc32            = 0x%08xu;\n",
                    static_cast<unsigned long long>(c.secretLen),
                    c.secretCrc32);
    }

    return candidates.size() == 1 ? 0 : 3;
}


// --- generate-observations ---

static int cmdGenerateObservations(const char *secret, int coordArgc, char **coordArgv) {
    if (coordArgc < 2 || coordArgc % 2 != 0) {
        std::fprintf(stderr, "generate-observations requires one or more x y pairs\n");
        return 1;
    }

    uint64_t secretLen = std::strlen(secret);
    uint32_t secretCrc = crc32String(secret);

    std::printf("# generated: secret len=%llu crc32=0x%08x\n"
                "# x y word0 word1\n",
                static_cast<unsigned long long>(secretLen), secretCrc);

    for (int i = 0; i < coordArgc; i += 2) {
        int x = 0, y = 0;
        if (!parseInt(coordArgv[i], &x) || !parseInt(coordArgv[i + 1], &y)) {
            std::fprintf(stderr, "Invalid coordinates: %s %s\n", coordArgv[i], coordArgv[i + 1]);
            return 1;
        }
        uint32_t seed = crc32Combine(crc32String(propertyPrefix(x, y)), secretCrc, secretLen);
        auto words = wordsFromSeed(seed, 2);
        std::printf("%d %d %s %s\n", x, y, words[0].c_str(), words[1].c_str());
    }

    return 0;
}


// --- Prediction ---

static bool haveCalibration() {
    if (!kHaveBuiltInCalibration) {
        std::fprintf(stderr, "No built-in calibration. Run `crc-fun calibrate` "
                             "and patch the printed constants into crc-fun.cpp.\n");
        return false;
    }
    return true;
}

static std::vector<std::string> predictWords(const std::string &prefix, int count) {
    uint32_t seed = crc32Combine(crc32String(prefix), kSecretCrc32, kSecretLen);
    return wordsFromSeed(seed, count);
}

static int cmdCurse(const char *email) {
    if (!haveCalibration()) return 1;
    auto words = predictWords(cursePrefix(email), 3);
    std::printf("%s_%s_%s\n", words[0].c_str(), words[1].c_str(), words[2].c_str());
    return 0;
}

static int cmdProperty(int x, int y) {
    if (!haveCalibration()) return 1;
    auto words = predictWords(propertyPrefix(x, y), 2);
    std::printf("%s %s\n", words[0].c_str(), words[1].c_str());
    return 0;
}

static int cmdFindProperty(const char *word0, const char *word1,
                           int cx, int cy, int radius, int limit) {
    if (!haveCalibration()) return 1;

    std::vector<std::string> target = {upperString(word0), upperString(word1)};
    if (!wordExists(target[0]) || !wordExists(target[1])) {
        std::fprintf(stderr, "Unknown target word(s): %s %s\n",
                     target[0].c_str(), target[1].c_str());
        return 1;
    }

    int found = 0;
    int64_t x0 = static_cast<int64_t>(cx) - radius;
    int64_t x1 = static_cast<int64_t>(cx) + radius;
    int64_t y0 = static_cast<int64_t>(cy) - radius;
    int64_t y1 = static_cast<int64_t>(cy) + radius;

    for (int64_t y = y0; y <= y1; y++) {
        for (int64_t x = x0; x <= x1; x++) {
            if (x < INT32_MIN || x > INT32_MAX || y < INT32_MIN || y > INT32_MAX) continue;
            auto words = predictWords(
                propertyPrefix(static_cast<int>(x), static_cast<int>(y)), 2);
            if (words == target) {
                std::printf("%d %d\n", static_cast<int>(x), static_cast<int>(y));
                if (++found == limit && limit > 0) return 0;
            }
        }
    }

    return found == 0 ? 2 : 0;
}


// --- find-curse-names ---

// Encodes the 8 least-significant base-26 digits of counter as lowercase
// letters into buf[0..7], null-terminated. Naturally wraps at 26^8 since
// higher bits are discarded -- so a random uint64_t start point works fine.
static void counterToFixedPart(uint64_t counter, char buf[9]) {
    for (int i = 7; i >= 0; i--) {
        buf[i] = static_cast<char>('a' + counter % 26);
        counter /= 26;
    }
    buf[8] = '\0';
}

static int cmdFindCurseNames(const char *atSuffix) {
    if (!haveCalibration()) return 1;

    std::string suffix(atSuffix);
    if (suffix.empty() || suffix[0] != '@') {
        std::fprintf(stderr, "Suffix must start with @, e.g. @example.com\n");
        return 1;
    }

    // cursePrefix(email) = email + "_", so the fixed part after the local part
    // is "@domain.com_" (including the underscore).
    std::string fixedSuffix    = suffix + "_";
    uint32_t    fixedSuffixCrc = crc32String(fixedSuffix);
    uint64_t    fixedSuffixLen = fixedSuffix.size();

    // Precompute the CRC32 shift operations as flat matrices so the hot loop
    // only needs two gf2MatrixTimes calls instead of full squaring each time.
    //
    //   seed = gf2MatrixTimes(matSecret,
    //              gf2MatrixTimes(matSuffix, CRC32(localpart))
    //              ^ fixedSuffixCrc)
    //          ^ kSecretCrc32
    uint32_t matSuffix[32], matSecret[32];
    buildShiftMatrix(fixedSuffixLen, matSuffix);
    buildShiftMatrix(kSecretLen,     matSecret);

    // Deduplication bitset: one bit per unique curse name.
    // Curse names are indexed as i0 + N*i1 + N*N*i2, where N = 201.
    const int      N          = static_cast<int>(curseWords().size()); // 201
    const uint32_t totalNames = static_cast<uint32_t>(N * N * N);     // 8,120,601
    const uint32_t bitWords   = (totalNames + 31) / 32;               // 253,769

    // atomic<uint32_t> allows lock-free fetch_or for check-and-set.
    std::vector<std::atomic<uint32_t>> seen(bitWords);
    for (auto &w : seen) w.store(0, std::memory_order_relaxed);

    // Start from a random point in the 26^8 space so repeated runs produce
    // different example emails for each curse name.
    uint64_t startCounter = 0;
    if (FILE *f = fopen("/dev/urandom", "rb")) {
        fread(&startCounter, sizeof(startCounter), 1, f);
        fclose(f);
    }

    std::atomic<uint32_t> foundCount(0);
    std::atomic<uint64_t> nextCounter(startCounter);
    std::atomic<bool>     done(false);
    std::mutex            printMutex;

    unsigned int nThreads = std::thread::hardware_concurrency();
    if (nThreads == 0) nThreads = 1;
    if (nThreads > 64) nThreads = 64;

    const uint64_t batchSize = 1ULL << 14; // 16384 — small enough for responsive done-checking

    auto started = std::chrono::steady_clock::now();

    std::thread progressThread([&, startCounter]() {
        while (!done.load(std::memory_order_relaxed)) {
            std::this_thread::sleep_for(std::chrono::seconds(5));
            uint32_t found  = foundCount.load(std::memory_order_relaxed);
            uint64_t tested = nextCounter.load(std::memory_order_relaxed) - startCounter;
            double   secs   = std::chrono::duration<double>(
                std::chrono::steady_clock::now() - started).count();
            std::fprintf(stderr, "  %u / %u names (%.1f%%), %.1fM parts/s\n",
                         found, totalNames, 100.0 * found / totalNames,
                         secs > 0 ? tested / secs / 1e6 : 0.0);
        }
    });

    std::vector<std::thread> workers;
    workers.reserve(nThreads);
    for (unsigned int t = 0; t < nThreads; t++) {
        workers.emplace_back([&]() {
            char buf[16];

            while (!done.load(std::memory_order_relaxed)) {
                uint64_t start = nextCounter.fetch_add(batchSize, std::memory_order_relaxed);

                for (uint64_t i = 0; i < batchSize; i++) {
                    counterToFixedPart(start + i, buf);

                    // Compute Jenkins seed via the precomputed matrices.
                    uint32_t localCrc  = crc32(reinterpret_cast<const unsigned char *>(buf), 8);
                    uint32_t prefixCrc = gf2MatrixTimes(matSuffix, localCrc) ^ fixedSuffixCrc;
                    uint32_t seed      = gf2MatrixTimes(matSecret, prefixCrc) ^ kSecretCrc32;

                    // Get word indices from Jenkins.
                    int idx[3];
                    {
                        JenkinsRandomSource rng(seed);
                        for (int j = 0; j < 3; j++) {
                            idx[j] = rng.getRandomBoundedInt(0, N - 1);
                        }
                    }

                    // Atomically mark this curse name as seen; skip if already found.
                    uint32_t nameIdx = static_cast<uint32_t>(idx[0])
                                     + static_cast<uint32_t>(N) * idx[1]
                                     + static_cast<uint32_t>(N * N) * idx[2];
                    uint32_t word = nameIdx / 32;
                    uint32_t bit  = 1u << (nameIdx % 32);
                    if (seen[word].fetch_or(bit, std::memory_order_relaxed) & bit) {
                        continue;
                    }

                    // First thread to find this name — print it.
                    const auto &words = curseWords();
                    uint32_t count = foundCount.fetch_add(1, std::memory_order_relaxed) + 1;
                    {
                        std::lock_guard<std::mutex> lock(printMutex);
                        std::printf("%s_%s_%s\t%s%s\n",
                                    words[idx[0]].c_str(),
                                    words[idx[1]].c_str(),
                                    words[idx[2]].c_str(),
                                    buf, suffix.c_str());
                    }
                    if (count >= totalNames) {
                        done.store(true, std::memory_order_relaxed);
                        return;
                    }
                }
            }
        });
    }

    for (auto &w : workers) w.join();
    done.store(true, std::memory_order_relaxed);
    progressThread.join();

    std::fflush(stdout);
    uint32_t found = foundCount.load();
    std::fprintf(stderr, "Done: %u / %u unique curse names (%.1f%%) for %s.\n",
                 found, totalNames, 100.0 * found / totalNames, suffix.c_str());
    return 0;
}


// --- Self-test ---

static bool selfTestCrcCombine() {
    for (int lenA = 0; lenA <= 96; lenA++) {
        for (int lenB = 0; lenB <= 96; lenB++) {
            std::string a, b;
            for (int i = 0; i < lenA; i++) a.push_back(static_cast<char>((i * 37 + lenB) & 0xff));
            for (int i = 0; i < lenB; i++) b.push_back(static_cast<char>((i * 53 + lenA) & 0xff));

            uint32_t direct   = crc32String(a + b);
            uint32_t combined = crc32Combine(crc32String(a), crc32String(b), b.size());
            if (direct != combined) {
                std::fprintf(stderr,
                             "CRC combine failed for lenA=%d lenB=%d: "
                             "direct=0x%08x combined=0x%08x\n",
                             lenA, lenB, direct, combined);
                return false;
            }
        }
    }
    return true;
}

static bool selfTestSecretFactoring() {
    const std::string fakeSecret = "airport-test-secret";
    const uint64_t    secretLen  = fakeSecret.size();
    const uint32_t    secretCrc  = crc32String(fakeSecret);

    // Verify factoring and recovery for a handful of prefixes
    for (const std::string &prefix : std::vector<std::string>{
            propertyPrefix(12345, -67890),
            propertyPrefix(-12, 34),
            cursePrefix("someone@example.com"),
            cursePrefix("same.length@example.net")}) {

        uint32_t direct   = crc32String(prefix + fakeSecret);
        uint32_t factored = crc32Combine(crc32String(prefix), secretCrc, secretLen);
        if (direct != factored) {
            std::fprintf(stderr,
                         "Secret factoring failed for prefix '%s': "
                         "direct=0x%08x factored=0x%08x\n",
                         prefix.c_str(), direct, factored);
            return false;
        }

        uint32_t recovered = direct ^ crc32Shift(crc32String(prefix), secretLen);
        if (recovered != secretCrc) {
            std::fprintf(stderr,
                         "Secret CRC recovery failed for prefix '%s': "
                         "expected=0x%08x recovered=0x%08x\n",
                         prefix.c_str(), secretCrc, recovered);
            return false;
        }
    }

    // Verify candidateMatchesAll with known-good and known-bad candidates
    std::vector<Observation> obs;
    for (const auto &coord : std::vector<std::pair<int,int>>{{12345, -67890}, {-12, 34}, {0, 0}}) {
        Observation o;
        o.x = coord.first;
        o.y = coord.second;
        o.prefix    = propertyPrefix(o.x, o.y);
        o.prefixCrc = crc32String(o.prefix);
        o.words     = wordsFromSeed(crc32String(o.prefix + fakeSecret), 2);
        obs.push_back(o);
    }

    Candidate good = {secretLen, secretCrc};
    if (!candidateMatchesAll(good, obs)) {
        std::fprintf(stderr, "Known-good calibration candidate failed\n");
        return false;
    }

    Candidate bad = {secretLen, secretCrc ^ 1u};
    if (candidateMatchesAll(bad, obs)) {
        std::fprintf(stderr, "Known-bad calibration candidate incorrectly passed\n");
        return false;
    }

    return true;
}

static int cmdSelfTest() {
    if (curseWords().empty()) {
        std::fprintf(stderr, "No curse words loaded from embedded list\n");
        return 1;
    }
    if (!selfTestCrcCombine()) return 1;
    if (!selfTestSecretFactoring()) return 1;
    std::printf("self-test passed; loaded %zu curse words\n", curseWords().size());
    return 0;
}


// --- Usage / main ---

static void usage(const char *prog) {
    std::fprintf(stderr,
                 "Usage:\n"
                 "  %s self-test\n"
                 "  %s generate-observations <secret> <x> <y> [<x> <y> ...]\n"
                 "  %s calibrate <observations.txt> [minSecretLen maxSecretLen]\n"
                 "  %s curse <email>\n"
                 "  %s property <x> <y>\n"
                 "  %s find-property <word0> <word1> <centerX> <centerY> <radius> [limit]\n"
                 "  %s find-curse-names <@suffix>\n"
                 "\n"
                 "Observation file format (from property gates at known global coords):\n"
                 "  # x y word0 word1\n"
                 "  12345 -67890 WHEAT LAKE\n",
                 prog, prog, prog, prog, prog, prog, prog);
}

int main(int argc, char **argv) {
    if (argc < 2) {
        usage(argv[0]);
        return 1;
    }

    std::string cmd = argv[1];

    if (cmd == "self-test") {
        if (argc != 2) { usage(argv[0]); return 1; }
        return cmdSelfTest();
    }

    if (cmd == "generate-observations") {
        if (argc < 5) { usage(argv[0]); return 1; }
        return cmdGenerateObservations(argv[2], argc - 3, argv + 3);
    }

    if (cmd == "calibrate") {
        if (argc != 3 && argc != 5) { usage(argv[0]); return 1; }
        uint64_t minLen = 1, maxLen = 256;
        if (argc == 5) {
            if (!parseUInt64(argv[3], &minLen) || !parseUInt64(argv[4], &maxLen) ||
                minLen == 0 || minLen > maxLen) {
                std::fprintf(stderr, "Invalid secret length range\n");
                return 1;
            }
        }
        return cmdCalibrate(argv[2], minLen, maxLen);
    }

    if (cmd == "curse") {
        if (argc != 3) { usage(argv[0]); return 1; }
        return cmdCurse(argv[2]);
    }

    if (cmd == "property") {
        if (argc != 4) { usage(argv[0]); return 1; }
        int x = 0, y = 0;
        if (!parseInt(argv[2], &x) || !parseInt(argv[3], &y)) {
            std::fprintf(stderr, "Invalid coordinates\n");
            return 1;
        }
        return cmdProperty(x, y);
    }

    if (cmd == "find-property") {
        if (argc != 7 && argc != 8) { usage(argv[0]); return 1; }
        int cx = 0, cy = 0, radius = 0, limit = 20;
        if (!parseInt(argv[4], &cx) || !parseInt(argv[5], &cy) ||
            !parseInt(argv[6], &radius) || radius < 0) {
            std::fprintf(stderr, "Invalid search area\n");
            return 1;
        }
        if (argc == 8 && (!parseInt(argv[7], &limit) || limit < 0)) {
            std::fprintf(stderr, "Invalid limit\n");
            return 1;
        }
        return cmdFindProperty(argv[2], argv[3], cx, cy, radius, limit);
    }

    if (cmd == "find-curse-names") {
        if (argc != 3) { usage(argv[0]); return 1; }
        return cmdFindCurseNames(argv[2]);
    }

    usage(argv[0]);
    return 1;
}
